# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f23c8648216a144c78b8fe2f102137494da167a23c9ba3976082c768600ecda0d6a8e7f0cac23f0a59d20571aaf672ea1094c5a45701fc5c71f08ada6176891

test:
  secret_key_base: 5755f4b1ba5418b8fbcd004de6d50966fd67a10f089d065624efc7619c43bd7c1ba08023ead9cd7927aa6cb0b46f9af9a9c80604e0c9d015ea0570a17dd0bc1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
